// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIRrOKu2C1hIcZWV8nI7gRttQnGsCL2XM',
    appId: '1:977187470029:web:1b79bbc216e11f748b0784',
    messagingSenderId: '977187470029',
    projectId: 'chat-app-5063c',
    authDomain: 'chat-app-5063c.firebaseapp.com',
    storageBucket: 'chat-app-5063c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIxNArAU5STubATY3GTYianJvQDNgJt_M',
    appId: '1:977187470029:android:e8c169c9846719178b0784',
    messagingSenderId: '977187470029',
    projectId: 'chat-app-5063c',
    storageBucket: 'chat-app-5063c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFXEIqN3Y0Wv2qz0LpQaZIK91GuGs-qa4',
    appId: '1:977187470029:ios:c013d6867ed321f08b0784',
    messagingSenderId: '977187470029',
    projectId: 'chat-app-5063c',
    storageBucket: 'chat-app-5063c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}